/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'brent.gardner' at '11/19/16 1:18 PM' with Gradle 3.1
 *
 * @author brent.gardner, @date 11/19/16 1:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
